// Local, self-contained dashboard assets. Agent text is rendered with textContent,
// never HTML. The browser can only read the existing recording endpoints.
export const agentMapPage = `<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Sandcastle · Agent map</title><link rel="stylesheet" href="/style.css"><script src="/app.js" defer></script></head>
<body>
<a class="skip-link" href="#main">Skip to workflow</a>
<header class="topbar"><div class="brand"><span class="brand-mark" aria-hidden="true">S</span><strong>Sandcastle</strong><span class="breadcrumb">/ Agent map</span></div><div class="connection-tools"><span id="connection" role="status">Connecting…</span><button id="pause" type="button" title="Pause dashboard updates, not agent execution">Pause updates</button><span class="local-badge">Local · read-only</span></div></header>
<div class="app-layout">
<aside class="sidebar" aria-label="Workflow navigation">
  <label class="field">Recorded session<select id="runs" aria-label="Recorded session"><option>No sessions yet</option></select></label>
  <label class="field">Batch<select id="batch" aria-label="Batch"><option value="latest">Latest batch</option></select></label>
  <details id="agent-sidebar" open><summary class="sidebar-heading">Agents <span id="agent-count" class="count">0</span></summary>
    <label class="field search-field"><span class="sr-only">Find agents</span><input id="agent-search" type="search" placeholder="Find issue, role or branch…" aria-label="Find agents"></label>
    <label class="field"><span class="sr-only">Agent status</span><select id="agent-status" aria-label="Agent status"><option value="all">All statuses</option><option value="running">Running</option><option value="attention">Needs attention</option><option value="completed">Completed</option><option value="queued">Queued</option></select></label>
    <nav id="jobs" aria-label="Agents in selected batch"></nav>
  </details>
  <p class="sidebar-note">Follow execution here.<br>Agents keep running when this page is closed or paused.</p>
</aside>
<main id="main" tabindex="-1">
  <div class="run-heading"><div><p class="eyebrow">WORKFLOW RUN</p><h1 id="run-title">Agent map</h1><p id="run-meta" class="muted">Waiting for a recorded session.</p></div><span id="run-status"></span></div>
  <section id="summary" class="summary" aria-label="Session summary"></section>
  <div class="tabs" role="tablist" aria-label="Run views"><button id="workflow-tab" role="tab" aria-selected="true" aria-controls="workflow-panel" tabindex="0">Workflow</button><button id="logs-tab" role="tab" aria-selected="false" aria-controls="logs-panel" tabindex="-1">Logs</button></div>
  <section id="workflow-panel" role="tabpanel" aria-labelledby="workflow-tab">
    <div class="section-heading"><div><h2 id="batch-title">Workflow</h2><p class="muted">Select an agent to inspect its output. Parallel lanes represent independent issues.</p></div></div>
    <div id="map" aria-label="Workflow map"></div>
    <details id="decisions" class="decisions"><summary id="decision-title">Planner decisions</summary><div id="decision-list"></div></details>
  </section>
  <section id="logs-panel" role="tabpanel" aria-labelledby="logs-tab" hidden>
    <div id="no-agent" class="empty"><h2>Select an agent</h2><p>Choose a job from the sidebar or workflow to inspect its recorded activity.</p></div>
    <div id="agent-details" hidden>
      <div class="agent-heading"><div><p id="agent-label" class="eyebrow"></p><h2 id="agent-title" tabindex="-1"></h2><p id="agent-meta" class="muted"></p></div><span id="agent-state"></span></div>
      <details id="metadata" class="metadata"><summary>Agent details &amp; usage</summary><dl id="agent-fields"></dl></details>
      <div class="log-panel">
        <div class="log-toolbar"><div class="log-search"><label class="sr-only" for="log-search">Search activity</label><input id="log-search" type="search" placeholder="Search recorded activity…"><span id="match-count" role="status"></span><button id="previous-match" type="button" aria-label="Previous match" title="Previous match">Previous</button><button id="next-match" type="button" aria-label="Next match" title="Next match">Next</button></div>
          <label class="sr-only" for="event-type">Event type</label><select id="event-type"><option value="all">All events</option><option value="toolCall">Tool calls</option><option value="text">Messages</option><option value="error">Agent error</option></select>
        </div>
        <div class="log-options"><div><label><input id="wrap" type="checkbox" checked> Wrap lines</label><label><input id="follow" type="checkbox" checked> Follow output</label><span id="event-count" class="muted"></span></div><div><button id="copy" type="button" aria-label="Copy visible activity">Copy visible</button><button id="download" type="button" aria-label="Download recorded activity">Download activity</button></div></div>
        <div id="log-output" class="log-output wrap" role="log" aria-label="Agent activity" aria-live="off" tabindex="0"></div>
        <div class="log-footer"><span>Recent activity · up to 150 events, 4,000 characters each · not the full raw log</span><span id="log-notice" role="status"></span></div>
      </div>
    </div>
  </section>
  <footer>Local observation only. Common credentials are filtered; review output before sharing it.</footer>
</main></div>
</body></html>`;

export const agentMapStyles = `
:root{color-scheme:dark;--bg:#0d1117;--surface:#161b22;--subtle:#21262d;--border:#30363d;--text:#e6edf3;--muted:#a1acb8;--blue:#79b8ff;--green:#56d364;--amber:#e3b341;--red:#ff7b72;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg);color:var(--text)}
*{box-sizing:border-box}body{margin:0}[hidden]{display:none!important}button,input,select{font:inherit;color:inherit}button,select,input[type=search]{border:1px solid var(--border);border-radius:6px;background:var(--surface);min-height:36px}button{padding:6px 12px;cursor:pointer;font-weight:550}button:hover{background:#292f38;border-color:#6e7681}button:disabled{opacity:.45;cursor:default}input[type=search]{padding:7px 12px;min-width:0;width:100%}select{padding:7px 30px 7px 10px;max-width:100%;text-overflow:ellipsis}input::placeholder{color:#9da7b3}input[type=checkbox]{accent-color:var(--blue);width:16px;height:16px;margin:0}button:focus-visible,input:focus-visible,select:focus-visible,summary:focus-visible,[tabindex]:focus-visible,a:focus-visible{outline:2px solid var(--blue);outline-offset:3px}a{color:var(--blue)}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}.skip-link{position:fixed;top:-60px;left:12px;z-index:5;background:var(--surface);padding:12px}.skip-link:focus{top:10px}
.topbar{min-height:68px;padding:12px 28px;display:flex;align-items:center;justify-content:space-between;gap:16px;background:#010409;border-bottom:1px solid var(--border)}.brand,.connection-tools{display:flex;align-items:center;gap:14px}.brand{font-size:17px}.brand-mark{display:grid;place-items:center;background:#cfeaaf;color:#22301c;width:34px;height:34px;border-radius:8px;font-weight:750;font-size:21px}.breadcrumb{color:var(--muted);font-size:15px}.connection-tools{font-size:13px}.local-badge{border:1px solid var(--border);padding:3px 8px;border-radius:20px;color:var(--muted)}#connection{color:var(--green)}#connection[data-state=offline]{color:var(--amber)}#connection[data-state=paused]{color:var(--muted)}
.app-layout{display:grid;grid-template-columns:272px minmax(0,1fr);min-height:calc(100vh - 68px)}.sidebar{padding:26px 18px;background:#0d1117;border-right:1px solid var(--border);min-width:0}.field{display:grid;gap:7px;font-size:14px;font-weight:550;margin-bottom:18px}.field select{width:100%;font-weight:400}.sidebar-heading{font-size:15px;font-weight:650;padding:12px 0;cursor:pointer;list-style-position:inside}.count{font-variant-numeric:tabular-nums;background:var(--subtle);border-radius:16px;padding:1px 8px;font-size:13px;margin-left:5px}.sidebar .search-field{margin:6px 0 10px}.sidebar-note{font-size:13px;color:var(--muted);line-height:1.7;border-top:1px solid var(--border);margin-top:24px;padding-top:18px}.job-group{margin:17px 0 7px;font-size:13px;font-weight:650;color:var(--muted)}.job{display:block;width:100%;text-align:left;background:transparent;border:1px solid transparent;border-radius:6px;margin:3px 0;padding:10px;font-size:14px}.job[aria-current=true]{background:#172c46;border-color:#388bfd;color:#fff}.job-top{display:flex;align-items:center;justify-content:space-between;gap:8px}.job-name{display:block;color:var(--muted);font-size:13px;font-weight:400;margin-top:4px;overflow-wrap:anywhere}.job .badge{font-size:11px;padding:1px 5px}.job-duration{font-size:12px;color:var(--muted);font-weight:400;margin-top:4px;display:block}
main{min-width:0;padding:28px 32px;max-width:1800px;width:100%;margin:0 auto}.run-heading,.agent-heading,.section-heading{display:flex;justify-content:space-between;align-items:flex-start;gap:18px}.run-heading>div,.agent-heading>div{min-width:0}h1{font-size:28px;line-height:1.25;letter-spacing:-.6px;margin:5px 0 10px;overflow-wrap:anywhere}h2{font-size:21px;line-height:1.4;margin:0 0 6px;overflow-wrap:anywhere}p{margin:0 0 12px}.eyebrow{font-size:12px;letter-spacing:1px;font-weight:650;color:var(--muted);margin:0 0 5px}.muted{color:var(--muted);font-size:14px}.run-heading>.badge{margin-top:24px}.summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border:1px solid var(--border);border-radius:8px;background:var(--surface);margin:20px 0 24px;overflow:hidden}.stat{padding:15px 20px;border-right:1px solid var(--border)}.stat:last-child{border:0}.stat span{display:block;color:var(--muted);font-size:13px}.stat strong{display:block;font-size:21px;font-weight:600;margin-top:4px;font-variant-numeric:tabular-nums}.stat.attention strong{color:var(--amber)}.tabs{display:flex;border-bottom:1px solid var(--border);gap:22px;margin-bottom:24px}.tabs button{border:0;border-bottom:3px solid transparent;border-radius:0;background:transparent;padding:10px 6px;font-size:15px}.tabs button[aria-selected=true]{border-color:#f78166;color:#fff}.tabs button:hover{background:var(--surface)}
.badge{display:inline-flex;align-items:center;white-space:nowrap;gap:6px;border:1px solid var(--border);border-radius:20px;padding:3px 9px;font-size:12px;font-weight:550;line-height:1.5;color:var(--muted);background:var(--surface)}.badge.running{color:var(--amber);border-color:#78602a;background:#2b2519}.badge.completed{color:var(--green);border-color:#285638;background:#12271c}.badge.failed,.badge.blocked,.badge.interrupted{color:var(--red);border-color:#79413f;background:#301c20}.badge.stopped,.badge.unknown{color:var(--amber)}
.map-scroll{overflow:auto;border:1px solid var(--border);border-radius:8px;background:var(--surface);padding:24px;margin:5px 0 24px}.graph{display:flex;gap:26px;align-items:center;min-height:150px}.stage{flex:0 0 190px;min-width:0;position:relative}.stage+.stage:before{content:"";position:absolute;left:-27px;top:50%;width:26px;border-top:1px solid #6e7681}.stage-label{font-size:13px;font-weight:650;color:var(--muted);margin-bottom:12px}.stage.pipelines{flex:1 0 400px}.lane{display:grid;grid-template-columns:minmax(180px,1fr) minmax(180px,1fr);gap:22px;padding:10px 0;position:relative}.lane .node+.node:before{content:"";position:absolute;width:22px;border-top:1px solid #6e7681;left:-23px;top:50%}.node{display:block;position:relative;text-align:left;width:100%;background:var(--bg);border:1px solid #454d57;border-radius:7px;padding:12px;margin:8px 0;min-width:0}.node[aria-pressed=true]{border-color:var(--blue);box-shadow:0 0 0 1px var(--blue);background:#13243a}.node-top{display:flex;justify-content:space-between;gap:8px;align-items:center;font-size:14px}.node p{font-size:14px;font-weight:400;margin:9px 0;color:var(--text);overflow-wrap:anywhere}.node small{font-size:12px;font-weight:400;color:var(--muted)}.node .badge{font-size:11px;padding:1px 6px}.node .issue-ref{color:var(--blue);font-weight:550}.decisions{border:1px solid var(--border);border-radius:8px;background:var(--surface)}.decisions>summary,.metadata>summary{padding:13px 16px;cursor:pointer;font-size:14px;font-weight:550}.decision{padding:15px 18px;border-top:1px solid var(--border)}.decision-top{display:flex;align-items:center;gap:10px;flex-wrap:wrap}.decision p{margin:8px 0 4px;font-size:14px;color:var(--muted)}.decision small{font-size:13px;color:var(--muted);overflow-wrap:anywhere}
.metadata{border:1px solid var(--border);border-radius:6px;margin:12px 0 20px}.metadata dl{display:grid;grid-template-columns:120px minmax(0,1fr);gap:8px 16px;padding:0 16px 16px;margin:0;font-size:14px}.metadata dt{color:var(--muted)}.metadata dd{margin:0;overflow-wrap:anywhere}.log-panel{border:1px solid var(--border);border-radius:8px;overflow:hidden;background:#010409}.log-toolbar{display:flex;align-items:center;gap:12px;padding:14px 16px;background:var(--surface);border-bottom:1px solid var(--border);flex-wrap:wrap}.log-search{display:flex;gap:6px;align-items:center;flex:1;min-width:280px}.log-search input{flex:1;min-width:130px}.log-search button{font-size:12px;padding:4px 8px}.log-search #match-count{font-size:12px;color:var(--muted);white-space:nowrap}.log-options{display:flex;gap:10px;justify-content:space-between;padding:10px 16px;background:#0d1117;border-bottom:1px solid var(--border);flex-wrap:wrap;font-size:13px}.log-options>div{display:flex;align-items:center;gap:14px;flex-wrap:wrap}.log-options label{display:flex;align-items:center;gap:7px;cursor:pointer;min-height:30px}.log-options button{font-size:13px}.log-output{height:clamp(300px,52vh,760px);overflow:auto;scrollbar-gutter:stable;font:14px/1.75 ui-monospace,SFMono-Regular,Consolas,"Liberation Mono",monospace;overscroll-behavior:contain}.log-row{display:grid;grid-template-columns:42px 86px 66px minmax(0,1fr);min-width:100%;width:max-content;padding:3px 14px 3px 0;border-left:3px solid transparent;align-items:start}.log-output.wrap .log-row{width:100%}.log-row:hover{background:#101820}.log-row.active-match{background:#1c2b3c;border-left-color:var(--blue)}.line-number{text-align:right;padding-right:10px;color:#8a96a3;user-select:none;font-size:12px}.log-time{color:#8a96a3;font-size:12px}.log-kind{font-size:11px;color:#9da9b5;line-height:24px}.log-text{margin:0;font:inherit;white-space:pre;min-width:0}.wrap .log-text{white-space:pre-wrap;overflow-wrap:anywhere}.log-row.error .log-text{color:var(--red)}mark{background:#67511a;color:#fff1bb;border-radius:2px}.log-footer{display:flex;justify-content:space-between;gap:12px;border-top:1px solid var(--border);padding:10px 16px;color:var(--muted);font-size:12px;flex-wrap:wrap}#log-notice{color:var(--blue)}.empty{padding:42px 24px;text-align:center;color:var(--muted);border:1px dashed var(--border);border-radius:8px}.empty h2{color:var(--text)}.empty p{max-width:560px;margin:8px auto}.log-output>.empty{border:0;padding:40px 20px;font:15px/1.5 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.sidebar .empty{font-size:13px;padding:18px 8px}footer{margin-top:28px;font-size:12px;color:var(--muted)}
@media(min-width:1500px){main{padding:32px 44px}.sidebar{padding:28px 22px}.app-layout{grid-template-columns:290px minmax(0,1fr)}}
@media(max-width:1050px){main{padding:24px}.app-layout{grid-template-columns:235px minmax(0,1fr)}.sidebar{padding:20px 12px}.connection-tools .local-badge{display:none}.stat{padding:12px}.log-search{flex-wrap:wrap}.log-search input{min-width:170px}.log-toolbar>select{width:100%}.log-options{padding:10px}.log-row{grid-template-columns:35px 74px minmax(0,1fr)}.log-kind{display:none}}
@media(max-width:760px){.topbar{padding:12px 16px;flex-wrap:wrap;gap:12px}.brand{font-size:16px}.breadcrumb{font-size:14px}.connection-tools{width:100%;justify-content:space-between}.app-layout{display:block}.sidebar{border-right:0;border-bottom:1px solid var(--border);padding:16px}.sidebar>.field{display:inline-grid;vertical-align:top;width:calc(50% - 6px);margin-bottom:8px}.sidebar>.field:first-child{margin-right:8px}.sidebar-note{display:none}main{padding:22px 16px}.run-heading{gap:10px}h1{font-size:24px}.summary{grid-template-columns:repeat(2,minmax(0,1fr));margin:16px 0}.stat{padding:12px 16px;border-bottom:1px solid var(--border)}.stat:nth-child(2){border-right:0}.stat:nth-child(n+3){border-bottom:0}.stat strong{font-size:20px}.map-scroll{padding:16px}.log-search{min-width:0;width:100%;flex-wrap:wrap}.log-search input{flex:1 0 100%;min-width:0}.log-toolbar{padding:12px}.log-options>div{gap:12px}.log-options button{min-height:40px}.log-row{grid-template-columns:32px minmax(0,1fr);padding-right:10px}.log-time{display:none}.log-output{font-size:14px;height:55vh;min-height:300px}.metadata dl{grid-template-columns:90px minmax(0,1fr)}.agent-heading{flex-wrap:wrap}.tabs button{min-height:44px}.field select,.field input{min-height:40px}}
.skip-link{top:10px;clip-path:inset(50%);width:1px;height:1px;overflow:hidden;padding:0;white-space:nowrap}.skip-link:focus{clip-path:none;width:auto;height:auto;padding:12px}
body[data-view=logs] .summary{display:none}body[data-view=logs] .tabs{margin-top:12px}
.lane>div{position:relative}.lane>div+div:before{content:"";position:absolute;width:22px;border-top:1px solid #6e7681;left:-23px;top:50%}
@media(min-width:761px){.sidebar{position:sticky;top:0;align-self:start;max-height:100vh;overflow-y:auto;min-height:calc(100vh - 68px)}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important}}
`;

export const agentMapScript = String.raw`
const $ = id => document.getElementById(id);
const el = (tag, text, cls) => { const node = document.createElement(tag); if(text !== undefined) node.textContent = text; if(cls) node.className = cls; return node; };
const attention = ['failed','blocked','stopped','interrupted','unknown'];
const title = value => value ? value.charAt(0).toUpperCase()+value.slice(1) : 'Unknown';
const stamp = value => { const date = new Date(value); return Number.isNaN(date.getTime()) ? 'Unknown time' : date.toLocaleString(); };
const time = value => { const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toLocaleTimeString([], {hour12:false}); };
const duration = node => { if(!node?.startedAt) return 'Not started'; const end=node.endedAt || (node.status==='running' ? new Date().toISOString() : current?.updatedAt); const seconds=Math.max(0,Math.floor((Date.parse(end)-Date.parse(node.startedAt))/1000)); if(!Number.isFinite(seconds)) return 'Unknown'; return seconds>=3600 ? Math.floor(seconds/3600)+'h '+Math.floor(seconds%3600/60)+'m' : Math.floor(seconds/60)+'m '+seconds%60+'s'; };
const json = async path => { const response=await fetch(path,{cache:'no-store'}); if(!response.ok) throw new Error('HTTP '+response.status); return response.json(); };
const initial = new URLSearchParams(location.hash.slice(1));
let runId=initial.get('run') || '', selectedId=initial.get('agent') || '', pane=initial.get('view')==='logs'?'logs':'workflow';
let batchChoice=initial.get('batch') || 'latest', current, selectedBatch=0, paused=false, timer, request=0, matchIndex=0, shownEvents=[], renderKey='', detailsKey='';
const badge = status => el('span',title(status),'badge '+status);
function linkState(){ const params=new URLSearchParams(); if(runId) params.set('run',runId); if(selectedId) params.set('agent',selectedId); if(pane==='logs') params.set('view',pane); if(batchChoice!=='latest') params.set('batch',batchChoice); history.replaceState(null,'','#'+params.toString()); }
function setPane(value){ pane=value; document.body.dataset.view=value; for(const name of ['workflow','logs']) { $(name+'-panel').hidden=name!==value; $(name+'-tab').setAttribute('aria-selected',String(name===value)); $(name+'-tab').tabIndex=name===value?0:-1; } if(value==='logs'){showDetails();if($('follow').checked&&!$('log-search').value.trim())$('log-output').scrollTop=$('log-output').scrollHeight;} linkState(); }
function selected(){ return current?.nodes.find(node=>node.id===selectedId); }
function selectAgent(node, moveFocus=false){ selectedId=node.id; batchChoice=String(node.batch);$('batch').value=batchChoice; $('log-search').value='';$('event-type').value='all';$('log-notice').textContent='';matchIndex=0;renderKey='';detailsKey='';render();setPane('logs');if(moveFocus)$('agent-title').focus({preventScroll:true}); }
function nodeLabel(node){return title(node.role)+(node.issueId?' · #'+node.issueId:'')+' · '+node.title+' · '+title(node.status);}
function card(node){ const button=el('button',undefined,'node');button.type='button';button.dataset.node=node.id;button.setAttribute('aria-label',nodeLabel(node));button.setAttribute('aria-pressed',String(selectedId===node.id));const top=el('div',undefined,'node-top');top.append(el('strong',title(node.role)),badge(node.status));button.append(top);if(node.issueId)button.append(el('small','#'+node.issueId,'issue-ref'));button.append(el('p',node.title),el('small',duration(node)));button.addEventListener('click',()=>selectAgent(node,true));return button; }
function renderJobs(nodes){const focus=document.activeElement?.dataset?.job;const jobs=$('jobs');jobs.replaceChildren();const query=$('agent-search').value.toLowerCase();const state=$('agent-status').value;const filtered=nodes.filter(node=>(state==='all'||(state==='attention'?attention.includes(node.status):node.status===state))&&[node.title,node.role,node.issueId,node.branch].join(' ').toLowerCase().includes(query));$('agent-count').textContent=filtered.length+' / '+nodes.length;
  if(!filtered.length){const empty=el('div',undefined,'empty');empty.append(el('p','No agents match these filters.'));if(query||state!=='all'){const clear=el('button','Clear agent filters');clear.onclick=()=>{$('agent-search').value='';$('agent-status').value='all';renderJobs(nodes);};empty.append(clear);}jobs.append(empty);return;}
  let group;for(const node of filtered){const next=node.issueId?'Issue #'+node.issueId:'Orchestration';if(group!==next){jobs.append(el('p',next,'job-group'));group=next;}const button=el('button',undefined,'job');button.type='button';button.dataset.job=node.id;button.setAttribute('aria-label',nodeLabel(node));button.setAttribute('aria-current',String(selectedId===node.id));const top=el('span',undefined,'job-top');top.append(el('strong',title(node.role)),badge(node.status));button.append(top,el('span',node.title,'job-name'),el('span',duration(node),'job-duration'));button.onclick=()=>selectAgent(node);jobs.append(button);}if(focus)Array.from(jobs.querySelectorAll('[data-job]')).find(button=>button.dataset.job===focus)?.focus({preventScroll:true});
}
function stage(label,nodes){const section=el('div',undefined,'stage');section.append(el('div',label,'stage-label'));for(const node of nodes)section.append(card(node));return section;}
function renderGraph(nodes){const focus=document.activeElement?.dataset?.node;const map=$('map');const scroll=map.firstElementChild?.scrollLeft || 0;map.replaceChildren();if(!nodes.length){map.append(el('div','No agents recorded in this batch yet.','empty'));return;}const container=el('div',undefined,'map-scroll');container.tabIndex=0;container.setAttribute('aria-label','Workflow stages; scroll horizontally to view all stages');const graph=el('div',undefined,'graph');const firstPlan=nodes.find(node=>node.role==='planner');const readinessNodes=nodes.filter(n=>n.role==='readiness');const before=readinessNodes.filter(node=>!firstPlan||nodes.indexOf(node)<nodes.indexOf(firstPlan));if(before.length)graph.append(stage('Readiness',before));const planners=nodes.filter(node=>node.role==='planner');if(planners.length)graph.append(stage('Plan',planners));const issues=[...new Set(nodes.filter(node=>node.issueId).map(node=>node.issueId))];if(issues.length){const pipelines=el('div',undefined,'stage pipelines');pipelines.append(el('div','Implement & review · parallel issues','stage-label'));for(const id of issues){const lane=el('div',undefined,'lane');for(const role of ['implementer','reviewer']){const column=el('div');for(const node of nodes.filter(node=>node.issueId===id&&node.role===role))column.append(card(node));lane.append(column);}pipelines.append(lane);}graph.append(pipelines);}const mergers=nodes.filter(node=>node.role==='merger');if(mergers.length)graph.append(stage('Integrate',mergers));const after=readinessNodes.filter(node=>!before.includes(node));if(after.length)graph.append(stage('Readiness',after));container.append(graph);map.append(container);container.scrollLeft=scroll;if(focus)Array.from(map.querySelectorAll('[data-node]')).find(button=>button.dataset.node===focus)?.focus({preventScroll:true});}
function renderDecisions(){const decisions=current?.batches.find(batch=>batch.number===selectedBatch)?.decisions || [];$('decisions').hidden=!decisions.length;$('decision-title').textContent='Planner decisions · '+decisions.length+' issues · '+decisions.filter(d=>d.disposition!=='selected').length+' deferred';const list=$('decision-list');list.replaceChildren();for(const decision of decisions){const item=el('div',undefined,'decision');const top=el('div',undefined,'decision-top');top.append(el('strong','#'+decision.id),el('span',decision.disposition,'badge'));item.append(top,el('p',decision.reason),el('small',decision.likelyAreas.join(', ')+(decision.conflictsWith?.length?' · Conflicts with '+decision.conflictsWith.map(id=>'#'+id).join(', '):'')));list.append(item);}}
function render(){const nodes=current?.nodes || [];$('run-title').textContent=current?.name || 'Agent map';$('run-meta').textContent=current?'Started '+stamp(current.startedAt)+' · '+current.id.slice(0,8)+(current.heartbeat==='stale'?' · Heartbeat stale; process state unknown':''):'Start an instrumented workflow to see agents and recorded activity here.';$('run-status').replaceChildren(...(current?[badge(current.status)]:[]));const summary=$('summary');summary.replaceChildren();for(const [label,value,cls] of [['Running',nodes.filter(n=>n.status==='running').length,''],['Completed',nodes.filter(n=>n.status==='completed').length,''],['Needs attention',nodes.filter(n=>attention.includes(n.status)).length,'attention'],['Batches',new Set(nodes.map(n=>n.batch)).size,'']]){const stat=el('div',undefined,'stat '+cls);stat.append(el('span',label),el('strong',String(value)));summary.append(stat);}const batches=[...new Set([...(current?.batches || []).map(b=>b.number),...nodes.map(n=>n.batch)])].sort((a,b)=>b-a);if(batchChoice!=='latest'&&!batches.includes(Number(batchChoice)))batchChoice='latest';selectedBatch=batchChoice==='latest'?(batches[0] || 0):Number(batchChoice);const picker=$('batch');const signature=batches.join(',');if(picker.dataset.signature!==signature){picker.replaceChildren(new Option('Latest batch','latest'),...batches.map(n=>new Option('Batch '+n,String(n))));picker.dataset.signature=signature;}picker.value=batchChoice;$('batch-title').textContent=selectedBatch?'Batch '+selectedBatch:'Workflow';if(!nodes.some(n=>n.id===selectedId&&(batchChoice!=='latest'||n.batch===selectedBatch))){selectedId=nodes.find(n=>n.batch===selectedBatch&&n.status==='running')?.id || nodes.find(n=>n.batch===selectedBatch&&attention.includes(n.status))?.id || nodes.filter(n=>n.batch===selectedBatch).at(-1)?.id || '';renderKey='';detailsKey='';}const members=nodes.filter(n=>n.batch===selectedBatch);renderJobs(members);renderGraph(members);renderDecisions();if(!current)$('map').replaceChildren(el('div','No recorded sessions. Run an instrumented Sandcastle workflow to get started.','empty'));showDetails();linkState();}
function eventsFor(node){if(!node)return [];const events=node.activity.map((event,index)=>({...event,line:index+1}));if(node.error)events.push({type:'error',timestamp:node.endedAt || node.startedAt,text:node.error,line:events.length+1});return events;}
function highlight(text,query){const fragment=document.createDocumentFragment();if(!query){fragment.append(document.createTextNode(text));return fragment;}const lower=text.toLowerCase(),needle=query.toLowerCase();let start=0,index;while((index=lower.indexOf(needle,start))!==-1){fragment.append(document.createTextNode(text.slice(start,index)),el('mark',text.slice(index,index+query.length)));start=index+query.length;}fragment.append(document.createTextNode(text.slice(start)));return fragment;}
function showDetails(){const node=selected();$('no-agent').hidden=!!node;$('agent-details').hidden=!node;if(!node){$('log-output').replaceChildren();shownEvents=[];return;}$('agent-label').textContent=title(node.role)+' · '+(node.issueId?'Issue #'+node.issueId:'Orchestration')+' · Batch '+node.batch;$('agent-title').textContent=node.title;$('agent-meta').textContent=(node.branch || 'Integration branch')+' · '+duration(node)+(node.model?' · '+node.model:'');$('agent-state').replaceChildren(badge(node.status));const key=JSON.stringify([node.id,node.branch,node.model,node.provider,node.sessionId,node.commits,node.usage]);if(key!==detailsKey){detailsKey=key;const values=[['Branch',node.branch||'Not reported'],['Provider',node.provider||'Not reported'],['Model',node.model||'Not reported'],['Session',node.sessionId||'Not reported'],['Commits',node.commits.join(', ')||'None recorded']];if(node.usage)values.push(['Last usage','Input '+node.usage.inputTokens.toLocaleString()+' · Output '+node.usage.outputTokens.toLocaleString()+' · Cache read '+node.usage.cacheReadInputTokens.toLocaleString()+' · Cache creation '+node.usage.cacheCreationInputTokens.toLocaleString()+' (last snapshot, not billed totals)']);$('agent-fields').replaceChildren();for(const [label,value] of values)$('agent-fields').append(el('dt',label),el('dd',value));}renderLog();}
function renderLog(){const node=selected(),events=eventsFor(node),query=$('log-search').value.trim(),kind=$('event-type').value;shownEvents=events.filter(event=>(kind==='all'||event.type===kind)&&(!query||event.text.toLowerCase().includes(query.toLowerCase())));const key=JSON.stringify([node?.id,events,query,kind]);$('event-count').textContent=shownEvents.length+' event'+(shownEvents.length===1?'':'s')+' shown';$('previous-match').disabled=$('next-match').disabled=!query||!shownEvents.length;$('copy').disabled=!shownEvents.length;$('download').disabled=!events.length;$('match-count').textContent=query?(shownEvents.length?Math.min(matchIndex+1,shownEvents.length)+' of '+shownEvents.length+' matches':'0 matches'):'';if(key===renderKey)return;renderKey=key;const output=$('log-output'),scroll=output.scrollTop;output.replaceChildren();if(!shownEvents.length){const empty=el('div',undefined,'empty');empty.append(el('h2',query||kind!=='all'?'No matching activity':'No activity received yet'),el('p',query||kind!=='all'?'Try another search or event type.':node?.status==='queued'?'This agent has not started.':'Recorded messages and tool calls will appear here.'));output.append(empty);return;}matchIndex=Math.min(matchIndex,shownEvents.length-1);for(const event of shownEvents){const row=el('div',undefined,'log-row '+(event.type==='error'?'error':''));row.dataset.line=String(event.line);row.append(el('span',String(event.line),'line-number'),el('span',time(event.timestamp),'log-time'),el('span',event.type==='toolCall'?'tool':event.type,'log-kind'));const text=el('pre',undefined,'log-text');text.append(highlight(event.text,query));row.append(text);output.append(row);}if(query)focusMatch(false);if($('follow').checked&&!query)output.scrollTop=output.scrollHeight;else output.scrollTop=scroll;}
function focusMatch(scroll=true){const rows=Array.from($('log-output').querySelectorAll('.log-row'));for(const [index,row] of rows.entries())row.classList.toggle('active-match',index===matchIndex);$('match-count').textContent=rows.length?(matchIndex+1)+' of '+rows.length+' matches':'0 matches';if(scroll&&rows[matchIndex]){const output=$('log-output'),row=rows[matchIndex];output.scrollTop+=row.getBoundingClientRect().top-output.getBoundingClientRect().top-36;}}
function activityText(events){return events.map(event=>'['+stamp(event.timestamp)+'] ['+event.type+'] '+event.text).join('\n');}
function resetRun(id){runId=id;current=undefined;selectedId='';batchChoice='latest';$('agent-search').value='';$('agent-status').value='all';$('log-search').value='';$('event-type').value='all';renderKey='';detailsKey='';matchIndex=0;render();}
async function refresh(){clearTimeout(timer);if(paused)return;const token=++request;try{const listing=await json('/api/runs');if(token!==request)return;if(!listing.runs.some(run=>run.id===runId))resetRun(listing.runs[0]?.id || '');const picker=$('runs'),signature=JSON.stringify(listing.runs.map(run=>[run.id,run.name,run.status]));if(picker.dataset.signature!==signature){picker.replaceChildren(...(listing.runs.length?listing.runs.map(run=>new Option(run.name+' · '+stamp(run.startedAt)+' · '+title(run.status),run.id)):[new Option('No sessions yet','')]));picker.dataset.signature=signature;}picker.value=runId;const expected=runId;const snapshot=runId?await json('/api/runs/'+runId):undefined;if(token!==request||expected!==runId)return;current=snapshot;render();$('connection').textContent='Live · '+time(new Date().toISOString());$('connection').dataset.state='live';}catch(error){if(token===request){$('connection').textContent='Connection lost · retrying';$('connection').dataset.state='offline';}}finally{if(token===request&&!paused)timer=setTimeout(refresh,1500);}}
$('runs').addEventListener('change',()=>{++request;resetRun($('runs').value);if(paused){paused=false;$('pause').textContent='Pause updates';}refresh();});
$('batch').addEventListener('change',()=>{batchChoice=$('batch').value;selectedId='';render();});
for(const id of ['agent-search','agent-status'])$(id).addEventListener(id==='agent-search'?'input':'change',()=>renderJobs((current?.nodes || []).filter(node=>node.batch===selectedBatch)));
for(const name of ['workflow','logs'])$(name+'-tab').addEventListener('click',()=>setPane(name));
document.querySelector('[role=tablist]').addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const origin=document.activeElement?.id==='workflow-tab'?'workflow':'logs';const next=event.key==='Home'?'workflow':event.key==='End'?'logs':origin==='workflow'?'logs':'workflow';setPane(next);$(next+'-tab').focus();});
$('log-search').addEventListener('input',()=>{matchIndex=0;renderLog();if($('log-search').value.trim()&&shownEvents.length)focusMatch();});
$('event-type').addEventListener('change',()=>{matchIndex=0;renderLog();});
$('next-match').onclick=()=>{if(shownEvents.length){matchIndex=(matchIndex+1)%shownEvents.length;focusMatch();}};
$('previous-match').onclick=()=>{if(shownEvents.length){matchIndex=(matchIndex-1+shownEvents.length)%shownEvents.length;focusMatch();}};
$('wrap').addEventListener('change',()=>$('log-output').classList.toggle('wrap',$('wrap').checked));
$('follow').addEventListener('change',()=>{if($('follow').checked)$('log-output').scrollTop=$('log-output').scrollHeight;});
$('log-output').addEventListener('scroll',()=>{const output=$('log-output');if(output.scrollHeight-output.clientHeight-output.scrollTop>40)$('follow').checked=false;});
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(activityText(shownEvents));$('log-notice').textContent='Visible activity copied';}catch{$('log-notice').textContent='Clipboard unavailable. Select and copy the output manually.';}};
$('download').onclick=()=>{const node=selected();if(!node)return;const text='Sandcastle recent recorded activity (not the full raw log)\nRun: '+runId+'\nAgent: '+node.title+'\nBranch: '+node.branch+'\n\n'+activityText(eventsFor(node));const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const anchor=el('a');anchor.href=url;anchor.download='sandcastle-'+runId.slice(0,8)+'-batch-'+node.batch+'-'+node.role+'.txt';document.body.append(anchor);anchor.click();anchor.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('pause').onclick=()=>{paused=!paused;++request;clearTimeout(timer);$('pause').textContent=paused?'Resume updates':'Pause updates';$('connection').textContent=paused?'Updates paused · agents still running':'Connecting…';$('connection').dataset.state=paused?'paused':'live';if(!paused)refresh();};
const mobileLayout=matchMedia('(max-width:760px)');
$('agent-sidebar').open=!mobileLayout.matches;
mobileLayout.addEventListener('change',event=>{$('agent-sidebar').open=!event.matches;});
setPane(pane);refresh();
`;
